// Generated by CIRCT firtool-1.75.0
module Arty35THarness(
  input CLK100MHZ,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:24:24]
  input ck_rst,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:25:24]
  inout led_0,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:28:24]
  inout led_1,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:29:24]
  inout led_2,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:30:24]
  inout led_3,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:31:24]
  inout led0_r,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:34:24]
  inout led0_g,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:35:24]
  inout led0_b,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:36:24]
  inout led1_r,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:38:24]
  inout led1_g,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:39:24]
  inout led1_b,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:40:24]
  inout led2_r,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:42:24]
  inout led2_g,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:43:24]
  inout led2_b,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:44:24]
  inout sw_0,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:47:24]
  inout sw_1,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:48:24]
  inout sw_2,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:49:24]
  inout sw_3,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:50:24]
  inout btn_0,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:53:24]
  inout btn_1,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:54:24]
  inout btn_2,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:55:24]
  inout btn_3,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:56:24]
  inout qspi_cs,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:59:24]
  inout qspi_sck,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:60:24]
  inout qspi_dq_0,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:61:24]
  inout qspi_dq_1,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:61:24]
  inout qspi_dq_2,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:61:24]
  inout qspi_dq_3,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:61:24]
  inout uart_rxd_out,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:64:24]
  inout uart_txd_in,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:65:24]
  inout ja_0,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:68:24]
  inout ja_1,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:69:24]
  inout ja_2,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:70:24]
  inout ja_3,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:71:24]
  inout ja_4,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:72:24]
  inout ja_5,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:73:24]
  inout ja_6,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:74:24]
  inout ja_7,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:75:24]
  inout jb_0,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:78:24]
  inout jb_1,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:79:24]
  inout jb_2,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:80:24]
  inout jb_3,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:81:24]
  inout jb_4,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:82:24]
  inout jb_5,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:83:24]
  inout jb_6,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:84:24]
  inout jb_7,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:85:24]
  inout jc_0,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:88:24]
  inout jc_1,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:89:24]
  inout jc_2,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:90:24]
  inout jc_3,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:91:24]
  inout jc_4,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:92:24]
  inout jc_5,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:93:24]
  inout jc_6,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:94:24]
  inout jc_7,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:95:24]
  inout jd_0,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:98:24]
  inout jd_1,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:99:24]
  inout jd_2,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:100:24]
  inout jd_3,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:101:24]
  inout jd_4,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:102:24]
  inout jd_5,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:103:24]
  inout jd_6,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:104:24]
  inout jd_7,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:105:24]
  inout ck_io_0,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_1,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_2,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_3,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_4,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_5,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_6,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_7,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_8,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_9,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_10,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_11,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_12,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_13,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_14,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_15,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_16,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_17,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_18,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_io_19,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:108:24]
  inout ck_miso,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:111:24]
  inout ck_mosi,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:112:24]
  inout ck_ss,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:113:24]
  inout ck_sck	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:114:24]
);

  wire _chiptop0_sjtag_reset_fpga_power_on_power_on_reset;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
  wire _SRST_n_pad_O;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
  wire _pad_2_O;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
  wire _pad_1_O;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
  wire _jtag_TCK_i_ival_pad_1_O;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:56:22]
  wire _jtag_TCK_i_ival_pad_O;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
  wire _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire _chiptop0_uart_0_rxd_pad_O;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
  wire _chiptop0_uart_0_txd;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire _chiptop0_jtag_TDO;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire _chiptop0_ndreset;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire _ip_mmcm_clk_out1;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
  wire _ip_mmcm_clk_out3;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
  wire _ip_mmcm_locked;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
  mmcm ip_mmcm (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
    .clk_in1  (CLK100MHZ),
    .clk_out1 (_ip_mmcm_clk_out1),
    .clk_out2 (/* unused */),
    .clk_out3 (_ip_mmcm_clk_out3),
    .resetn   (ck_rst),
    .locked   (_ip_mmcm_locked)
  );	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
  reset_sys ip_reset_sys (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:161:28]
    .slowest_sync_clk     (_ip_mmcm_clk_out1),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
    .ext_reset_in         (ck_rst & _SRST_n_pad_O),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21, fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:164:46]
    .aux_reset_in         (1'h1),
    .mb_debug_sys_rst     (_chiptop0_ndreset),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .dcm_locked           (_ip_mmcm_locked),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
    .mb_reset             (/* unused */),
    .bus_struct_reset     (/* unused */),
    .peripheral_reset     (/* unused */),
    .interconnect_aresetn (/* unused */),
    .peripheral_aresetn   (/* unused */)
  );	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:161:28]
  ChipTop chiptop0 (	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .uart_0_txd   (_chiptop0_uart_0_txd),
    .uart_0_rxd   (_chiptop0_uart_0_rxd_pad_O),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
    .custom_boot  (_plusarg_reader_out),	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .jtag_TCK     (_jtag_TCK_i_ival_pad_1_O),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:56:22]
    .jtag_TMS     (_pad_1_O),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
    .jtag_TDI     (_pad_2_O),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
    .jtag_TDO     (_chiptop0_jtag_TDO),
    .ndreset      (_chiptop0_ndreset),
    .sjtag_reset  (_chiptop0_sjtag_reset_fpga_power_on_power_on_reset),	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
    .reset_io     (~ck_rst),	// @[fpga/src/main/scala/arty/TestHarness.scala:16:13]
    .clock_uncore (_ip_mmcm_clk_out3),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
    .clock_tap    (/* unused */)
  );	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  IOBUF pad (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:278:21]
    .O  (/* unused */),
    .IO (uart_rxd_out),
    .I  (_chiptop0_uart_0_txd),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .T  (1'h0)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:278:21]
  IOBUF chiptop0_uart_0_rxd_pad (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
    .O  (_chiptop0_uart_0_rxd_pad_O),
    .IO (uart_txd_in),
    .I  (1'h0),
    .T  (1'h1)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("custom_boot_pin=%d"),
    .WIDTH(1)
  ) plusarg_reader (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  IOBUF jtag_TCK_i_ival_pad (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
    .O  (_jtag_TCK_i_ival_pad_O),
    .IO (jd_2),
    .I  (1'h0),
    .T  (1'h1)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
  IBUFG jtag_TCK_i_ival_pad_1 (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:56:22]
    .O (_jtag_TCK_i_ival_pad_1_O),
    .I (_jtag_TCK_i_ival_pad_O)	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:56:22]
  IOBUF pad_1 (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
    .O  (_pad_1_O),
    .IO (jd_5),
    .I  (1'h0),
    .T  (1'h1)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
  PULLUP pullup_0 (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:381:24]
    .O (jd_5)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:381:24]
  IOBUF pad_2 (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
    .O  (_pad_2_O),
    .IO (jd_4),
    .I  (1'h0),
    .T  (1'h1)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
  PULLUP pullup_1 (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:381:24]
    .O (jd_4)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:381:24]
  IOBUF pad_3 (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
    .O  (/* unused */),
    .IO (jd_0),
    .I  (_chiptop0_jtag_TDO),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .T  (1'h0)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:268:23]
  IOBUF SRST_n_pad (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
    .O  (_SRST_n_pad_O),
    .IO (jd_6),
    .I  (1'h0),
    .T  (1'h1)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:286:21]
  PULLUP pullup_2 (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:381:24]
    .O (jd_6)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Unisim.scala:381:24]
  PowerOnResetFPGAOnly chiptop0_sjtag_reset_fpga_power_on (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
    .clock          (_ip_mmcm_clk_out3),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
    .power_on_reset (_chiptop0_sjtag_reset_fpga_power_on_power_on_reset)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
  ResetCatchAndSync_d3 harnessBinderReset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (_ip_mmcm_clk_out3),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:147:23]
    .reset         (~ck_rst),	// @[fpga/src/main/scala/arty/TestHarness.scala:16:13]
    .io_sync_reset (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
endmodule

