// Generated by CIRCT firtool-1.75.0
module BundleBridgeNexus_UInt1_1();	// @[generators/diplomacy/diplomacy/src/diplomacy/bundlebridge/BundleBridgeNexus.scala:20:9]
  wire outputs_0 = 1'h0;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:78:32]
endmodule

