// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ChipTop(	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  output uart_0_txd,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input  uart_0_rxd,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input  custom_boot,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input  jtag_TCK,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input  jtag_TMS,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input  jtag_TDI,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output jtag_TDO,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output ndreset,	// @[fpga/src/main/scala/arty/IOBinders.scala:12:30]
  input  sjtag_reset,	// @[fpga/src/main/scala/arty/IOBinders.scala:17:34]
  input  reset_io,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:87:24]
  input  clock_uncore,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:95:26]
  output clock_tap	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
);

  wire _iocell_jtag_TCK_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire _iocell_jtag_TMS_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire _iocell_jtag_TDI_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire _gated_clock_debug_clock_gate_out;	// @[generators/rocket-chip/src/main/scala/util/ClockGate.scala:36:20]
  wire _dmactiveAck_dmactiveAck_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _debug_reset_syncd_debug_reset_sync_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire _iocell_custom_boot_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire _iocell_uart_0_rxd_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire _system_auto_cbus_fixedClockNode_anon_out_clock;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_auto_cbus_fixedClockNode_anon_out_reset;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_debug_systemjtag_jtag_TDO_data;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_debug_dmactive;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_uart_0_txd;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire _system_clock_tap;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire debug_reset = ~_debug_reset_syncd_debug_reset_sync_io_q;	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  reg  clock_en;	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
  always @(posedge _system_auto_cbus_fixedClockNode_anon_out_clock or posedge debug_reset) begin	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
    if (debug_reset)	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
      clock_en <= 1'h1;	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
    else	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
      clock_en <= _dmactiveAck_dmactiveAck_io_q;	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
      `FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    initial begin	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
        `INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
        clock_en = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
      `endif // RANDOMIZE_REG_INIT
      if (debug_reset)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
        clock_en = 1'h1;	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
      `FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  DigitalTop system (	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_clock (clock_uncore),
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_reset (reset_io),
    .auto_cbus_fixedClockNode_anon_out_clock                                           (_system_auto_cbus_fixedClockNode_anon_out_clock),
    .auto_cbus_fixedClockNode_anon_out_reset                                           (_system_auto_cbus_fixedClockNode_anon_out_reset),
    .resetctrl_hartIsInReset_0                                                         (_system_auto_cbus_fixedClockNode_anon_out_reset),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .debug_clock                                                                       (_gated_clock_debug_clock_gate_out),	// @[generators/rocket-chip/src/main/scala/util/ClockGate.scala:36:20]
    .debug_reset                                                                       (debug_reset),	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
    .debug_systemjtag_jtag_TCK                                                         (_iocell_jtag_TCK_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .debug_systemjtag_jtag_TMS                                                         (_iocell_jtag_TMS_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .debug_systemjtag_jtag_TDI                                                         (_iocell_jtag_TDI_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .debug_systemjtag_jtag_TDO_data                                                    (_system_debug_systemjtag_jtag_TDO_data),
    .debug_systemjtag_reset                                                            (sjtag_reset),
    .debug_ndreset                                                                     (ndreset),
    .debug_dmactive                                                                    (_system_debug_dmactive),
    .debug_dmactiveAck                                                                 (_dmactiveAck_dmactiveAck_io_q),	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .custom_boot                                                                       (_iocell_custom_boot_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .uart_0_txd                                                                        (_system_uart_0_txd),
    .uart_0_rxd                                                                        (_iocell_uart_0_rxd_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .clock_tap                                                                         (_system_clock_tap)
  );	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  GenericDigitalInIOCell iocell_uart_0_rxd (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (uart_0_rxd),
    .i   (_iocell_uart_0_rxd_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalOutIOCell iocell_uart_0_txd (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (uart_0_txd),
    .o   (_system_uart_0_txd),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalInIOCell iocell_custom_boot (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (custom_boot),
    .i   (_iocell_custom_boot_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  ResetCatchAndSync_d3 system_debug_systemjtag_reset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (_iocell_jtag_TCK_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .reset         (_system_auto_cbus_fixedClockNode_anon_out_reset),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .io_sync_reset (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  AsyncResetSynchronizerShiftReg_w1_d3_i0 debug_reset_syncd_debug_reset_sync (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (_system_auto_cbus_fixedClockNode_anon_out_clock),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .reset (sjtag_reset),
    .io_d  (1'h1),	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    .io_q  (_debug_reset_syncd_debug_reset_sync_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  ResetSynchronizerShiftReg_w1_d3_i0 dmactiveAck_dmactiveAck (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (_system_auto_cbus_fixedClockNode_anon_out_clock),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .reset (debug_reset),	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:290:40]
    .io_d  (_system_debug_dmactive),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .io_q  (_dmactiveAck_dmactiveAck_io_q)
  );	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  EICG_wrapper gated_clock_debug_clock_gate (	// @[generators/rocket-chip/src/main/scala/util/ClockGate.scala:36:20]
    .in      (_system_auto_cbus_fixedClockNode_anon_out_clock),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .test_en (1'h0),	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
    .en      (clock_en),	// @[generators/rocket-chip/src/main/scala/devices/debug/Periphery.scala:298:29]
    .out     (_gated_clock_debug_clock_gate_out)
  );	// @[generators/rocket-chip/src/main/scala/util/ClockGate.scala:36:20]
  GenericDigitalOutIOCell iocell_jtag_TDO (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (jtag_TDO),
    .o   (_system_debug_systemjtag_jtag_TDO_data),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalInIOCell iocell_jtag_TDI (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (jtag_TDI),
    .i   (_iocell_jtag_TDI_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_jtag_TMS (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (jtag_TMS),
    .i   (_iocell_jtag_TMS_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_jtag_TCK (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (jtag_TCK),
    .i   (_iocell_jtag_TCK_i),
    .ie  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalOutIOCell iocell_clock_tap (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (clock_tap),
    .o   (_system_clock_tap),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
endmodule

