// Generated by CIRCT firtool-1.75.0
module SystemBus(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  input         auto_coupler_to_serv_tile_0_widget_anon_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [30:0] auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_serv_tile_0_widget_anon_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_serv_tile_0_widget_anon_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [30:0] auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_bus_named_fbus_bus_xing_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [30:0] auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_from_bus_named_fbus_bus_xing_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_bus_named_fbus_bus_xing_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_bus_named_cbus_bus_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_bus_named_cbus_bus_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [28:0] auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_bus_named_cbus_bus_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_bus_named_cbus_bus_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_1_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_1_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_sbus_clock_groups_in_member_sbus_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_sbus_clock_groups_in_member_sbus_0_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_param;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [3:0]  _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [30:0] _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_address;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_bufferable;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_modifiable;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_readalloc;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_writealloc;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_privileged;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_secure;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_fetch;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [3:0]  _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_mask;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [31:0] _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_corrupt;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_bus_named_fbus_auto_widget_anon_out_d_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_bus_named_cbus_auto_widget_anon_in_a_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_bus_named_cbus_auto_widget_anon_in_d_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [1:0]  _coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_param;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [3:0]  _coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_sink;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_denied;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [31:0] _coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_corrupt;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _fixer_auto_anon_in_0_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_in_0_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [2:0]  _fixer_auto_anon_in_0_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [1:0]  _fixer_auto_anon_in_0_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [3:0]  _fixer_auto_anon_in_0_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_in_0_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_in_0_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [31:0] _fixer_auto_anon_in_0_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_in_0_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [2:0]  _fixer_auto_anon_out_1_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [2:0]  _fixer_auto_anon_out_1_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [3:0]  _fixer_auto_anon_out_1_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [1:0]  _fixer_auto_anon_out_1_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [30:0] _fixer_auto_anon_out_1_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_a_bits_user_amba_prot_bufferable;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_a_bits_user_amba_prot_modifiable;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_a_bits_user_amba_prot_readalloc;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_a_bits_user_amba_prot_writealloc;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_a_bits_user_amba_prot_privileged;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_a_bits_user_amba_prot_secure;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_a_bits_user_amba_prot_fetch;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [3:0]  _fixer_auto_anon_out_1_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [31:0] _fixer_auto_anon_out_1_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_1_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [2:0]  _fixer_auto_anon_out_0_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [2:0]  _fixer_auto_anon_out_0_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [3:0]  _fixer_auto_anon_out_0_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [30:0] _fixer_auto_anon_out_0_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_bits_user_amba_prot_bufferable;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_bits_user_amba_prot_modifiable;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_bits_user_amba_prot_readalloc;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_bits_user_amba_prot_writealloc;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_bits_user_amba_prot_privileged;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_bits_user_amba_prot_secure;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_bits_user_amba_prot_fetch;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [3:0]  _fixer_auto_anon_out_0_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire [31:0] _fixer_auto_anon_out_0_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _fixer_auto_anon_out_0_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  wire        _system_bus_xbar_auto_anon_in_1_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_in_1_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [2:0]  _system_bus_xbar_auto_anon_in_1_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [1:0]  _system_bus_xbar_auto_anon_in_1_d_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [3:0]  _system_bus_xbar_auto_anon_in_1_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [1:0]  _system_bus_xbar_auto_anon_in_1_d_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_in_1_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_in_1_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [31:0] _system_bus_xbar_auto_anon_in_1_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_in_1_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_in_0_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_in_0_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [2:0]  _system_bus_xbar_auto_anon_in_0_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [1:0]  _system_bus_xbar_auto_anon_in_0_d_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [3:0]  _system_bus_xbar_auto_anon_in_0_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_in_0_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_in_0_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [31:0] _system_bus_xbar_auto_anon_in_0_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_in_0_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_out_0_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [2:0]  _system_bus_xbar_auto_anon_out_0_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [2:0]  _system_bus_xbar_auto_anon_out_0_a_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [3:0]  _system_bus_xbar_auto_anon_out_0_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [2:0]  _system_bus_xbar_auto_anon_out_0_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [28:0] _system_bus_xbar_auto_anon_out_0_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [3:0]  _system_bus_xbar_auto_anon_out_0_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire [31:0] _system_bus_xbar_auto_anon_out_0_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_out_0_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _system_bus_xbar_auto_anon_out_0_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  wire        _fixedClockNode_auto_anon_out_0_clock;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  wire        _fixedClockNode_auto_anon_out_0_reset;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  FixedClockBroadcast_4 fixedClockNode (	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_anon_in_clock    (auto_sbus_clock_groups_in_member_sbus_0_clock),
    .auto_anon_in_reset    (auto_sbus_clock_groups_in_member_sbus_0_reset),
    .auto_anon_out_2_clock (auto_fixedClockNode_anon_out_1_clock),
    .auto_anon_out_2_reset (auto_fixedClockNode_anon_out_1_reset),
    .auto_anon_out_0_clock (_fixedClockNode_auto_anon_out_0_clock),
    .auto_anon_out_0_reset (_fixedClockNode_auto_anon_out_0_reset)
  );	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  TLXbar_sbus_i2_o2_a31d32s3k1z4u system_bus_xbar (	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .clock                                            (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                                            (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_anon_in_1_a_ready                           (_system_bus_xbar_auto_anon_in_1_a_ready),
    .auto_anon_in_1_a_valid                           (_fixer_auto_anon_out_1_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_opcode                     (_fixer_auto_anon_out_1_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_param                      (_fixer_auto_anon_out_1_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_size                       (_fixer_auto_anon_out_1_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_source                     (_fixer_auto_anon_out_1_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_address                    (_fixer_auto_anon_out_1_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_user_amba_prot_bufferable  (_fixer_auto_anon_out_1_a_bits_user_amba_prot_bufferable),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_user_amba_prot_modifiable  (_fixer_auto_anon_out_1_a_bits_user_amba_prot_modifiable),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_user_amba_prot_readalloc   (_fixer_auto_anon_out_1_a_bits_user_amba_prot_readalloc),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_user_amba_prot_writealloc  (_fixer_auto_anon_out_1_a_bits_user_amba_prot_writealloc),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_user_amba_prot_privileged  (_fixer_auto_anon_out_1_a_bits_user_amba_prot_privileged),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_user_amba_prot_secure      (_fixer_auto_anon_out_1_a_bits_user_amba_prot_secure),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_user_amba_prot_fetch       (_fixer_auto_anon_out_1_a_bits_user_amba_prot_fetch),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_mask                       (_fixer_auto_anon_out_1_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_data                       (_fixer_auto_anon_out_1_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_a_bits_corrupt                    (_fixer_auto_anon_out_1_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_d_ready                           (_fixer_auto_anon_out_1_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_1_d_valid                           (_system_bus_xbar_auto_anon_in_1_d_valid),
    .auto_anon_in_1_d_bits_opcode                     (_system_bus_xbar_auto_anon_in_1_d_bits_opcode),
    .auto_anon_in_1_d_bits_param                      (_system_bus_xbar_auto_anon_in_1_d_bits_param),
    .auto_anon_in_1_d_bits_size                       (_system_bus_xbar_auto_anon_in_1_d_bits_size),
    .auto_anon_in_1_d_bits_source                     (_system_bus_xbar_auto_anon_in_1_d_bits_source),
    .auto_anon_in_1_d_bits_sink                       (_system_bus_xbar_auto_anon_in_1_d_bits_sink),
    .auto_anon_in_1_d_bits_denied                     (_system_bus_xbar_auto_anon_in_1_d_bits_denied),
    .auto_anon_in_1_d_bits_data                       (_system_bus_xbar_auto_anon_in_1_d_bits_data),
    .auto_anon_in_1_d_bits_corrupt                    (_system_bus_xbar_auto_anon_in_1_d_bits_corrupt),
    .auto_anon_in_0_a_ready                           (_system_bus_xbar_auto_anon_in_0_a_ready),
    .auto_anon_in_0_a_valid                           (_fixer_auto_anon_out_0_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_opcode                     (_fixer_auto_anon_out_0_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_param                      (_fixer_auto_anon_out_0_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_size                       (_fixer_auto_anon_out_0_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_source                     (_fixer_auto_anon_out_0_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_address                    (_fixer_auto_anon_out_0_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_user_amba_prot_bufferable  (_fixer_auto_anon_out_0_a_bits_user_amba_prot_bufferable),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_user_amba_prot_modifiable  (_fixer_auto_anon_out_0_a_bits_user_amba_prot_modifiable),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_user_amba_prot_readalloc   (_fixer_auto_anon_out_0_a_bits_user_amba_prot_readalloc),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_user_amba_prot_writealloc  (_fixer_auto_anon_out_0_a_bits_user_amba_prot_writealloc),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_user_amba_prot_privileged  (_fixer_auto_anon_out_0_a_bits_user_amba_prot_privileged),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_user_amba_prot_secure      (_fixer_auto_anon_out_0_a_bits_user_amba_prot_secure),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_user_amba_prot_fetch       (_fixer_auto_anon_out_0_a_bits_user_amba_prot_fetch),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_mask                       (_fixer_auto_anon_out_0_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_data                       (_fixer_auto_anon_out_0_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_a_bits_corrupt                    (_fixer_auto_anon_out_0_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_d_ready                           (_fixer_auto_anon_out_0_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_anon_in_0_d_valid                           (_system_bus_xbar_auto_anon_in_0_d_valid),
    .auto_anon_in_0_d_bits_opcode                     (_system_bus_xbar_auto_anon_in_0_d_bits_opcode),
    .auto_anon_in_0_d_bits_param                      (_system_bus_xbar_auto_anon_in_0_d_bits_param),
    .auto_anon_in_0_d_bits_size                       (_system_bus_xbar_auto_anon_in_0_d_bits_size),
    .auto_anon_in_0_d_bits_sink                       (_system_bus_xbar_auto_anon_in_0_d_bits_sink),
    .auto_anon_in_0_d_bits_denied                     (_system_bus_xbar_auto_anon_in_0_d_bits_denied),
    .auto_anon_in_0_d_bits_data                       (_system_bus_xbar_auto_anon_in_0_d_bits_data),
    .auto_anon_in_0_d_bits_corrupt                    (_system_bus_xbar_auto_anon_in_0_d_bits_corrupt),
    .auto_anon_out_1_a_ready                          (auto_coupler_to_serv_tile_0_widget_anon_out_a_ready),
    .auto_anon_out_1_a_valid                          (auto_coupler_to_serv_tile_0_widget_anon_out_a_valid),
    .auto_anon_out_1_a_bits_opcode                    (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_opcode),
    .auto_anon_out_1_a_bits_param                     (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_param),
    .auto_anon_out_1_a_bits_size                      (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_size),
    .auto_anon_out_1_a_bits_source                    (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_source),
    .auto_anon_out_1_a_bits_address                   (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_address),
    .auto_anon_out_1_a_bits_user_amba_prot_bufferable (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_bufferable),
    .auto_anon_out_1_a_bits_user_amba_prot_modifiable (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_modifiable),
    .auto_anon_out_1_a_bits_user_amba_prot_readalloc  (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_readalloc),
    .auto_anon_out_1_a_bits_user_amba_prot_writealloc (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_writealloc),
    .auto_anon_out_1_a_bits_user_amba_prot_privileged (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_privileged),
    .auto_anon_out_1_a_bits_user_amba_prot_secure     (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_secure),
    .auto_anon_out_1_a_bits_user_amba_prot_fetch      (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_user_amba_prot_fetch),
    .auto_anon_out_1_a_bits_mask                      (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_mask),
    .auto_anon_out_1_a_bits_data                      (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_data),
    .auto_anon_out_1_a_bits_corrupt                   (auto_coupler_to_serv_tile_0_widget_anon_out_a_bits_corrupt),
    .auto_anon_out_1_d_ready                          (auto_coupler_to_serv_tile_0_widget_anon_out_d_ready),
    .auto_anon_out_1_d_valid                          (auto_coupler_to_serv_tile_0_widget_anon_out_d_valid),
    .auto_anon_out_1_d_bits_opcode                    (auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_opcode),
    .auto_anon_out_1_d_bits_size                      (auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_size),
    .auto_anon_out_1_d_bits_source                    (auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_source),
    .auto_anon_out_1_d_bits_denied                    (auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_denied),
    .auto_anon_out_1_d_bits_data                      (auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_data),
    .auto_anon_out_1_d_bits_corrupt                   (auto_coupler_to_serv_tile_0_widget_anon_out_d_bits_corrupt),
    .auto_anon_out_0_a_ready                          (_coupler_to_bus_named_cbus_auto_widget_anon_in_a_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_a_valid                          (_system_bus_xbar_auto_anon_out_0_a_valid),
    .auto_anon_out_0_a_bits_opcode                    (_system_bus_xbar_auto_anon_out_0_a_bits_opcode),
    .auto_anon_out_0_a_bits_param                     (_system_bus_xbar_auto_anon_out_0_a_bits_param),
    .auto_anon_out_0_a_bits_size                      (_system_bus_xbar_auto_anon_out_0_a_bits_size),
    .auto_anon_out_0_a_bits_source                    (_system_bus_xbar_auto_anon_out_0_a_bits_source),
    .auto_anon_out_0_a_bits_address                   (_system_bus_xbar_auto_anon_out_0_a_bits_address),
    .auto_anon_out_0_a_bits_mask                      (_system_bus_xbar_auto_anon_out_0_a_bits_mask),
    .auto_anon_out_0_a_bits_data                      (_system_bus_xbar_auto_anon_out_0_a_bits_data),
    .auto_anon_out_0_a_bits_corrupt                   (_system_bus_xbar_auto_anon_out_0_a_bits_corrupt),
    .auto_anon_out_0_d_ready                          (_system_bus_xbar_auto_anon_out_0_d_ready),
    .auto_anon_out_0_d_valid                          (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_opcode                    (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_param                     (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_param),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_size                      (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_source                    (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_sink                      (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_sink),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_denied                    (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_denied),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_data                      (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_data),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_corrupt                   (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_corrupt)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  );	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  TLFIFOFixer fixer (	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .clock                                            (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                                            (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_anon_in_1_a_ready                           (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_ready),
    .auto_anon_in_1_a_valid                           (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_valid),
    .auto_anon_in_1_a_bits_opcode                     (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_opcode),
    .auto_anon_in_1_a_bits_param                      (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_param),
    .auto_anon_in_1_a_bits_size                       (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_size),
    .auto_anon_in_1_a_bits_source                     (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_source),
    .auto_anon_in_1_a_bits_address                    (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_address),
    .auto_anon_in_1_a_bits_user_amba_prot_bufferable  (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_bufferable),
    .auto_anon_in_1_a_bits_user_amba_prot_modifiable  (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_modifiable),
    .auto_anon_in_1_a_bits_user_amba_prot_readalloc   (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_readalloc),
    .auto_anon_in_1_a_bits_user_amba_prot_writealloc  (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_writealloc),
    .auto_anon_in_1_a_bits_user_amba_prot_privileged  (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_privileged),
    .auto_anon_in_1_a_bits_user_amba_prot_secure      (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_secure),
    .auto_anon_in_1_a_bits_user_amba_prot_fetch       (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_user_amba_prot_fetch),
    .auto_anon_in_1_a_bits_mask                       (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_mask),
    .auto_anon_in_1_a_bits_data                       (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_data),
    .auto_anon_in_1_a_bits_corrupt                    (auto_coupler_from_serv_tile_tl_master_clock_xing_in_a_bits_corrupt),
    .auto_anon_in_1_d_ready                           (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_ready),
    .auto_anon_in_1_d_valid                           (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_valid),
    .auto_anon_in_1_d_bits_opcode                     (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_opcode),
    .auto_anon_in_1_d_bits_param                      (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_param),
    .auto_anon_in_1_d_bits_size                       (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_size),
    .auto_anon_in_1_d_bits_source                     (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_source),
    .auto_anon_in_1_d_bits_sink                       (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_sink),
    .auto_anon_in_1_d_bits_denied                     (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_denied),
    .auto_anon_in_1_d_bits_data                       (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_data),
    .auto_anon_in_1_d_bits_corrupt                    (auto_coupler_from_serv_tile_tl_master_clock_xing_in_d_bits_corrupt),
    .auto_anon_in_0_a_ready                           (_fixer_auto_anon_in_0_a_ready),
    .auto_anon_in_0_a_valid                           (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_opcode                     (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_param                      (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_param),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_size                       (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_source                     (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_address                    (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_address),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_user_amba_prot_bufferable  (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_bufferable),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_user_amba_prot_modifiable  (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_modifiable),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_user_amba_prot_readalloc   (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_readalloc),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_user_amba_prot_writealloc  (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_writealloc),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_user_amba_prot_privileged  (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_privileged),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_user_amba_prot_secure      (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_secure),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_user_amba_prot_fetch       (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_fetch),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_mask                       (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_mask),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_data                       (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_data),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_a_bits_corrupt                    (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_corrupt),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_d_ready                           (_coupler_from_bus_named_fbus_auto_widget_anon_out_d_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_0_d_valid                           (_fixer_auto_anon_in_0_d_valid),
    .auto_anon_in_0_d_bits_opcode                     (_fixer_auto_anon_in_0_d_bits_opcode),
    .auto_anon_in_0_d_bits_param                      (_fixer_auto_anon_in_0_d_bits_param),
    .auto_anon_in_0_d_bits_size                       (_fixer_auto_anon_in_0_d_bits_size),
    .auto_anon_in_0_d_bits_sink                       (_fixer_auto_anon_in_0_d_bits_sink),
    .auto_anon_in_0_d_bits_denied                     (_fixer_auto_anon_in_0_d_bits_denied),
    .auto_anon_in_0_d_bits_data                       (_fixer_auto_anon_in_0_d_bits_data),
    .auto_anon_in_0_d_bits_corrupt                    (_fixer_auto_anon_in_0_d_bits_corrupt),
    .auto_anon_out_1_a_ready                          (_system_bus_xbar_auto_anon_in_1_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_1_a_valid                          (_fixer_auto_anon_out_1_a_valid),
    .auto_anon_out_1_a_bits_opcode                    (_fixer_auto_anon_out_1_a_bits_opcode),
    .auto_anon_out_1_a_bits_param                     (_fixer_auto_anon_out_1_a_bits_param),
    .auto_anon_out_1_a_bits_size                      (_fixer_auto_anon_out_1_a_bits_size),
    .auto_anon_out_1_a_bits_source                    (_fixer_auto_anon_out_1_a_bits_source),
    .auto_anon_out_1_a_bits_address                   (_fixer_auto_anon_out_1_a_bits_address),
    .auto_anon_out_1_a_bits_user_amba_prot_bufferable (_fixer_auto_anon_out_1_a_bits_user_amba_prot_bufferable),
    .auto_anon_out_1_a_bits_user_amba_prot_modifiable (_fixer_auto_anon_out_1_a_bits_user_amba_prot_modifiable),
    .auto_anon_out_1_a_bits_user_amba_prot_readalloc  (_fixer_auto_anon_out_1_a_bits_user_amba_prot_readalloc),
    .auto_anon_out_1_a_bits_user_amba_prot_writealloc (_fixer_auto_anon_out_1_a_bits_user_amba_prot_writealloc),
    .auto_anon_out_1_a_bits_user_amba_prot_privileged (_fixer_auto_anon_out_1_a_bits_user_amba_prot_privileged),
    .auto_anon_out_1_a_bits_user_amba_prot_secure     (_fixer_auto_anon_out_1_a_bits_user_amba_prot_secure),
    .auto_anon_out_1_a_bits_user_amba_prot_fetch      (_fixer_auto_anon_out_1_a_bits_user_amba_prot_fetch),
    .auto_anon_out_1_a_bits_mask                      (_fixer_auto_anon_out_1_a_bits_mask),
    .auto_anon_out_1_a_bits_data                      (_fixer_auto_anon_out_1_a_bits_data),
    .auto_anon_out_1_a_bits_corrupt                   (_fixer_auto_anon_out_1_a_bits_corrupt),
    .auto_anon_out_1_d_ready                          (_fixer_auto_anon_out_1_d_ready),
    .auto_anon_out_1_d_valid                          (_system_bus_xbar_auto_anon_in_1_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_1_d_bits_opcode                    (_system_bus_xbar_auto_anon_in_1_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_1_d_bits_param                     (_system_bus_xbar_auto_anon_in_1_d_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_1_d_bits_size                      (_system_bus_xbar_auto_anon_in_1_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_1_d_bits_source                    (_system_bus_xbar_auto_anon_in_1_d_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_1_d_bits_sink                      (_system_bus_xbar_auto_anon_in_1_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_1_d_bits_denied                    (_system_bus_xbar_auto_anon_in_1_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_1_d_bits_data                      (_system_bus_xbar_auto_anon_in_1_d_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_1_d_bits_corrupt                   (_system_bus_xbar_auto_anon_in_1_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_0_a_ready                          (_system_bus_xbar_auto_anon_in_0_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_0_a_valid                          (_fixer_auto_anon_out_0_a_valid),
    .auto_anon_out_0_a_bits_opcode                    (_fixer_auto_anon_out_0_a_bits_opcode),
    .auto_anon_out_0_a_bits_param                     (_fixer_auto_anon_out_0_a_bits_param),
    .auto_anon_out_0_a_bits_size                      (_fixer_auto_anon_out_0_a_bits_size),
    .auto_anon_out_0_a_bits_source                    (_fixer_auto_anon_out_0_a_bits_source),
    .auto_anon_out_0_a_bits_address                   (_fixer_auto_anon_out_0_a_bits_address),
    .auto_anon_out_0_a_bits_user_amba_prot_bufferable (_fixer_auto_anon_out_0_a_bits_user_amba_prot_bufferable),
    .auto_anon_out_0_a_bits_user_amba_prot_modifiable (_fixer_auto_anon_out_0_a_bits_user_amba_prot_modifiable),
    .auto_anon_out_0_a_bits_user_amba_prot_readalloc  (_fixer_auto_anon_out_0_a_bits_user_amba_prot_readalloc),
    .auto_anon_out_0_a_bits_user_amba_prot_writealloc (_fixer_auto_anon_out_0_a_bits_user_amba_prot_writealloc),
    .auto_anon_out_0_a_bits_user_amba_prot_privileged (_fixer_auto_anon_out_0_a_bits_user_amba_prot_privileged),
    .auto_anon_out_0_a_bits_user_amba_prot_secure     (_fixer_auto_anon_out_0_a_bits_user_amba_prot_secure),
    .auto_anon_out_0_a_bits_user_amba_prot_fetch      (_fixer_auto_anon_out_0_a_bits_user_amba_prot_fetch),
    .auto_anon_out_0_a_bits_mask                      (_fixer_auto_anon_out_0_a_bits_mask),
    .auto_anon_out_0_a_bits_data                      (_fixer_auto_anon_out_0_a_bits_data),
    .auto_anon_out_0_a_bits_corrupt                   (_fixer_auto_anon_out_0_a_bits_corrupt),
    .auto_anon_out_0_d_ready                          (_fixer_auto_anon_out_0_d_ready),
    .auto_anon_out_0_d_valid                          (_system_bus_xbar_auto_anon_in_0_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_0_d_bits_opcode                    (_system_bus_xbar_auto_anon_in_0_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_0_d_bits_param                     (_system_bus_xbar_auto_anon_in_0_d_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_0_d_bits_size                      (_system_bus_xbar_auto_anon_in_0_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_0_d_bits_sink                      (_system_bus_xbar_auto_anon_in_0_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_0_d_bits_denied                    (_system_bus_xbar_auto_anon_in_0_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_0_d_bits_data                      (_system_bus_xbar_auto_anon_in_0_d_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_anon_out_0_d_bits_corrupt                   (_system_bus_xbar_auto_anon_in_0_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
  TLInterconnectCoupler_sbus_to_bus_named_cbus coupler_to_bus_named_cbus (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                              (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                              (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_widget_anon_in_a_ready        (_coupler_to_bus_named_cbus_auto_widget_anon_in_a_ready),
    .auto_widget_anon_in_a_valid        (_system_bus_xbar_auto_anon_out_0_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_a_bits_opcode  (_system_bus_xbar_auto_anon_out_0_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_a_bits_param   (_system_bus_xbar_auto_anon_out_0_a_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_a_bits_size    (_system_bus_xbar_auto_anon_out_0_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_a_bits_source  (_system_bus_xbar_auto_anon_out_0_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_a_bits_address (_system_bus_xbar_auto_anon_out_0_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_a_bits_mask    (_system_bus_xbar_auto_anon_out_0_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_a_bits_data    (_system_bus_xbar_auto_anon_out_0_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_a_bits_corrupt (_system_bus_xbar_auto_anon_out_0_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_d_ready        (_system_bus_xbar_auto_anon_out_0_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:47:43]
    .auto_widget_anon_in_d_valid        (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_valid),
    .auto_widget_anon_in_d_bits_opcode  (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_opcode),
    .auto_widget_anon_in_d_bits_param   (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_param),
    .auto_widget_anon_in_d_bits_size    (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_size),
    .auto_widget_anon_in_d_bits_source  (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_source),
    .auto_widget_anon_in_d_bits_sink    (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_sink),
    .auto_widget_anon_in_d_bits_denied  (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_denied),
    .auto_widget_anon_in_d_bits_data    (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_data),
    .auto_widget_anon_in_d_bits_corrupt (_coupler_to_bus_named_cbus_auto_widget_anon_in_d_bits_corrupt),
    .auto_bus_xing_out_a_ready          (auto_coupler_to_bus_named_cbus_bus_xing_out_a_ready),
    .auto_bus_xing_out_a_valid          (auto_coupler_to_bus_named_cbus_bus_xing_out_a_valid),
    .auto_bus_xing_out_a_bits_opcode    (auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_opcode),
    .auto_bus_xing_out_a_bits_param     (auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_param),
    .auto_bus_xing_out_a_bits_size      (auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_size),
    .auto_bus_xing_out_a_bits_source    (auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_source),
    .auto_bus_xing_out_a_bits_address   (auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_address),
    .auto_bus_xing_out_a_bits_mask      (auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_mask),
    .auto_bus_xing_out_a_bits_data      (auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_data),
    .auto_bus_xing_out_a_bits_corrupt   (auto_coupler_to_bus_named_cbus_bus_xing_out_a_bits_corrupt),
    .auto_bus_xing_out_d_ready          (auto_coupler_to_bus_named_cbus_bus_xing_out_d_ready),
    .auto_bus_xing_out_d_valid          (auto_coupler_to_bus_named_cbus_bus_xing_out_d_valid),
    .auto_bus_xing_out_d_bits_opcode    (auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_opcode),
    .auto_bus_xing_out_d_bits_param     (auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_param),
    .auto_bus_xing_out_d_bits_size      (auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_size),
    .auto_bus_xing_out_d_bits_source    (auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_source),
    .auto_bus_xing_out_d_bits_sink      (auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_sink),
    .auto_bus_xing_out_d_bits_denied    (auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_denied),
    .auto_bus_xing_out_d_bits_data      (auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_data),
    .auto_bus_xing_out_d_bits_corrupt   (auto_coupler_to_bus_named_cbus_bus_xing_out_d_bits_corrupt)
  );	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  TLInterconnectCoupler_sbus_from_bus_named_fbus coupler_from_bus_named_fbus (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                                                 (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                                                 (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_widget_anon_out_a_ready                          (_fixer_auto_anon_in_0_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_widget_anon_out_a_valid                          (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_valid),
    .auto_widget_anon_out_a_bits_opcode                    (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_opcode),
    .auto_widget_anon_out_a_bits_param                     (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_param),
    .auto_widget_anon_out_a_bits_size                      (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_size),
    .auto_widget_anon_out_a_bits_source                    (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_source),
    .auto_widget_anon_out_a_bits_address                   (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_address),
    .auto_widget_anon_out_a_bits_user_amba_prot_bufferable (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_bufferable),
    .auto_widget_anon_out_a_bits_user_amba_prot_modifiable (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_modifiable),
    .auto_widget_anon_out_a_bits_user_amba_prot_readalloc  (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_readalloc),
    .auto_widget_anon_out_a_bits_user_amba_prot_writealloc (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_writealloc),
    .auto_widget_anon_out_a_bits_user_amba_prot_privileged (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_privileged),
    .auto_widget_anon_out_a_bits_user_amba_prot_secure     (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_secure),
    .auto_widget_anon_out_a_bits_user_amba_prot_fetch      (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_user_amba_prot_fetch),
    .auto_widget_anon_out_a_bits_mask                      (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_mask),
    .auto_widget_anon_out_a_bits_data                      (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_data),
    .auto_widget_anon_out_a_bits_corrupt                   (_coupler_from_bus_named_fbus_auto_widget_anon_out_a_bits_corrupt),
    .auto_widget_anon_out_d_ready                          (_coupler_from_bus_named_fbus_auto_widget_anon_out_d_ready),
    .auto_widget_anon_out_d_valid                          (_fixer_auto_anon_in_0_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_widget_anon_out_d_bits_opcode                    (_fixer_auto_anon_in_0_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_widget_anon_out_d_bits_param                     (_fixer_auto_anon_in_0_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_widget_anon_out_d_bits_size                      (_fixer_auto_anon_in_0_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_widget_anon_out_d_bits_sink                      (_fixer_auto_anon_in_0_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_widget_anon_out_d_bits_denied                    (_fixer_auto_anon_in_0_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_widget_anon_out_d_bits_data                      (_fixer_auto_anon_in_0_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_widget_anon_out_d_bits_corrupt                   (_fixer_auto_anon_in_0_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:152:27]
    .auto_bus_xing_in_a_ready                              (auto_coupler_from_bus_named_fbus_bus_xing_in_a_ready),
    .auto_bus_xing_in_a_valid                              (auto_coupler_from_bus_named_fbus_bus_xing_in_a_valid),
    .auto_bus_xing_in_a_bits_opcode                        (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_opcode),
    .auto_bus_xing_in_a_bits_param                         (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_param),
    .auto_bus_xing_in_a_bits_size                          (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_size),
    .auto_bus_xing_in_a_bits_source                        (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_source),
    .auto_bus_xing_in_a_bits_address                       (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_address),
    .auto_bus_xing_in_a_bits_user_amba_prot_bufferable     (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_bufferable),
    .auto_bus_xing_in_a_bits_user_amba_prot_modifiable     (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_modifiable),
    .auto_bus_xing_in_a_bits_user_amba_prot_readalloc      (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_readalloc),
    .auto_bus_xing_in_a_bits_user_amba_prot_writealloc     (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_writealloc),
    .auto_bus_xing_in_a_bits_user_amba_prot_privileged     (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_privileged),
    .auto_bus_xing_in_a_bits_user_amba_prot_secure         (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_secure),
    .auto_bus_xing_in_a_bits_user_amba_prot_fetch          (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_user_amba_prot_fetch),
    .auto_bus_xing_in_a_bits_mask                          (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_mask),
    .auto_bus_xing_in_a_bits_data                          (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_data),
    .auto_bus_xing_in_a_bits_corrupt                       (auto_coupler_from_bus_named_fbus_bus_xing_in_a_bits_corrupt),
    .auto_bus_xing_in_d_ready                              (auto_coupler_from_bus_named_fbus_bus_xing_in_d_ready),
    .auto_bus_xing_in_d_valid                              (auto_coupler_from_bus_named_fbus_bus_xing_in_d_valid),
    .auto_bus_xing_in_d_bits_opcode                        (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_opcode),
    .auto_bus_xing_in_d_bits_param                         (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_param),
    .auto_bus_xing_in_d_bits_size                          (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_size),
    .auto_bus_xing_in_d_bits_sink                          (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_sink),
    .auto_bus_xing_in_d_bits_denied                        (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_denied),
    .auto_bus_xing_in_d_bits_data                          (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_data),
    .auto_bus_xing_in_d_bits_corrupt                       (auto_coupler_from_bus_named_fbus_bus_xing_in_d_bits_corrupt)
  );	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
endmodule

