// Generated by CIRCT firtool-1.75.0
module TilePRCIDomain(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  output        auto_element_reset_domain_serv_tile_tap_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_element_reset_domain_serv_tile_tap_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_element_reset_domain_serv_tile_tap_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_element_reset_domain_serv_tile_tap_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_element_reset_domain_serv_tile_tap_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [30:0] auto_element_reset_domain_serv_tile_tap_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_element_reset_domain_serv_tile_tap_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_element_reset_domain_serv_tile_tap_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_element_reset_domain_serv_tile_tap_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_element_reset_domain_serv_tile_tap_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_element_reset_domain_serv_tile_tap_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_element_reset_domain_serv_tile_tap_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_element_reset_domain_serv_tile_tap_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_element_reset_domain_serv_tile_tap_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_element_reset_domain_serv_tile_tap_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_element_reset_domain_serv_tile_tap_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_int_in_clock_xing_in_0_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_master_clock_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_tl_master_clock_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_tl_master_clock_xing_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_tl_master_clock_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_tl_master_clock_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [30:0] auto_tl_master_clock_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_tl_master_clock_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_tl_master_clock_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_tl_master_clock_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_master_clock_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_tl_master_clock_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_tl_master_clock_xing_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_tl_master_clock_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_tl_master_clock_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_master_clock_xing_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_master_clock_xing_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_tl_master_clock_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tl_master_clock_xing_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tap_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_tap_clock_in_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire        _intsink_1_auto_out_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
  wire        _buffer_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [2:0]  _buffer_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [1:0]  _buffer_auto_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [3:0]  _buffer_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [1:0]  _buffer_auto_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [31:0] _buffer_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire [2:0]  _element_reset_domain_serv_tile_auto_buffer_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire [2:0]  _element_reset_domain_serv_tile_auto_buffer_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire [3:0]  _element_reset_domain_serv_tile_auto_buffer_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire [1:0]  _element_reset_domain_serv_tile_auto_buffer_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire [30:0] _element_reset_domain_serv_tile_auto_buffer_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_bufferable;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_modifiable;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_readalloc;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_writealloc;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_privileged;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_secure;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_fetch;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire [3:0]  _element_reset_domain_serv_tile_auto_buffer_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire [31:0] _element_reset_domain_serv_tile_auto_buffer_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  wire        _element_reset_domain_serv_tile_auto_buffer_out_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  ServTile element_reset_domain_serv_tile (	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .clock                                            (auto_tap_clock_in_clock),
    .reset                                            (auto_tap_clock_in_reset),
    .auto_buffer_out_a_ready                          (_buffer_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_buffer_out_a_valid                          (_element_reset_domain_serv_tile_auto_buffer_out_a_valid),
    .auto_buffer_out_a_bits_opcode                    (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_opcode),
    .auto_buffer_out_a_bits_param                     (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_param),
    .auto_buffer_out_a_bits_size                      (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_size),
    .auto_buffer_out_a_bits_source                    (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_source),
    .auto_buffer_out_a_bits_address                   (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_address),
    .auto_buffer_out_a_bits_user_amba_prot_bufferable (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_bufferable),
    .auto_buffer_out_a_bits_user_amba_prot_modifiable (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_modifiable),
    .auto_buffer_out_a_bits_user_amba_prot_readalloc  (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_readalloc),
    .auto_buffer_out_a_bits_user_amba_prot_writealloc (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_writealloc),
    .auto_buffer_out_a_bits_user_amba_prot_privileged (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_privileged),
    .auto_buffer_out_a_bits_user_amba_prot_secure     (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_secure),
    .auto_buffer_out_a_bits_user_amba_prot_fetch      (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_fetch),
    .auto_buffer_out_a_bits_mask                      (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_mask),
    .auto_buffer_out_a_bits_data                      (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_data),
    .auto_buffer_out_a_bits_corrupt                   (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_corrupt),
    .auto_buffer_out_d_ready                          (_element_reset_domain_serv_tile_auto_buffer_out_d_ready),
    .auto_buffer_out_d_valid                          (_buffer_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_buffer_out_d_bits_opcode                    (_buffer_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_buffer_out_d_bits_param                     (_buffer_auto_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_buffer_out_d_bits_size                      (_buffer_auto_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_buffer_out_d_bits_source                    (_buffer_auto_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_buffer_out_d_bits_sink                      (_buffer_auto_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_buffer_out_d_bits_denied                    (_buffer_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_buffer_out_d_bits_data                      (_buffer_auto_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_buffer_out_d_bits_corrupt                   (_buffer_auto_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_tap_in_a_ready                              (auto_element_reset_domain_serv_tile_tap_in_a_ready),
    .auto_tap_in_a_valid                              (auto_element_reset_domain_serv_tile_tap_in_a_valid),
    .auto_tap_in_a_bits_opcode                        (auto_element_reset_domain_serv_tile_tap_in_a_bits_opcode),
    .auto_tap_in_a_bits_param                         (auto_element_reset_domain_serv_tile_tap_in_a_bits_param),
    .auto_tap_in_a_bits_size                          (auto_element_reset_domain_serv_tile_tap_in_a_bits_size),
    .auto_tap_in_a_bits_source                        (auto_element_reset_domain_serv_tile_tap_in_a_bits_source),
    .auto_tap_in_a_bits_address                       (auto_element_reset_domain_serv_tile_tap_in_a_bits_address),
    .auto_tap_in_a_bits_user_amba_prot_bufferable     (auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_bufferable),
    .auto_tap_in_a_bits_user_amba_prot_modifiable     (auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_modifiable),
    .auto_tap_in_a_bits_user_amba_prot_readalloc      (auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_readalloc),
    .auto_tap_in_a_bits_user_amba_prot_writealloc     (auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_writealloc),
    .auto_tap_in_a_bits_user_amba_prot_privileged     (auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_privileged),
    .auto_tap_in_a_bits_user_amba_prot_secure         (auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_secure),
    .auto_tap_in_a_bits_user_amba_prot_fetch          (auto_element_reset_domain_serv_tile_tap_in_a_bits_user_amba_prot_fetch),
    .auto_tap_in_a_bits_mask                          (auto_element_reset_domain_serv_tile_tap_in_a_bits_mask),
    .auto_tap_in_a_bits_data                          (auto_element_reset_domain_serv_tile_tap_in_a_bits_data),
    .auto_tap_in_a_bits_corrupt                       (auto_element_reset_domain_serv_tile_tap_in_a_bits_corrupt),
    .auto_tap_in_d_ready                              (auto_element_reset_domain_serv_tile_tap_in_d_ready),
    .auto_tap_in_d_valid                              (auto_element_reset_domain_serv_tile_tap_in_d_valid),
    .auto_tap_in_d_bits_opcode                        (auto_element_reset_domain_serv_tile_tap_in_d_bits_opcode),
    .auto_tap_in_d_bits_size                          (auto_element_reset_domain_serv_tile_tap_in_d_bits_size),
    .auto_tap_in_d_bits_source                        (auto_element_reset_domain_serv_tile_tap_in_d_bits_source),
    .auto_tap_in_d_bits_denied                        (auto_element_reset_domain_serv_tile_tap_in_d_bits_denied),
    .auto_tap_in_d_bits_data                          (auto_element_reset_domain_serv_tile_tap_in_d_bits_data),
    .auto_tap_in_d_bits_corrupt                       (auto_element_reset_domain_serv_tile_tap_in_d_bits_corrupt),
    .auto_int_local_in_1_0                            (_intsink_1_auto_out_0)	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
  );	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
  TLBuffer_a31d32s2k1z4u_2 buffer (	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .clock                                     (auto_tap_clock_in_clock),
    .reset                                     (auto_tap_clock_in_reset),
    .auto_in_a_ready                           (_buffer_auto_in_a_ready),
    .auto_in_a_valid                           (_element_reset_domain_serv_tile_auto_buffer_out_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_opcode                     (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_param                      (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_size                       (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_source                     (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_address                    (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_user_amba_prot_bufferable  (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_bufferable),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_user_amba_prot_modifiable  (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_modifiable),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_user_amba_prot_readalloc   (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_readalloc),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_user_amba_prot_writealloc  (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_writealloc),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_user_amba_prot_privileged  (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_privileged),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_user_amba_prot_secure      (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_secure),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_user_amba_prot_fetch       (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_user_amba_prot_fetch),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_mask                       (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_data                       (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_a_bits_corrupt                    (_element_reset_domain_serv_tile_auto_buffer_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_d_ready                           (_element_reset_domain_serv_tile_auto_buffer_out_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_in_d_valid                           (_buffer_auto_in_d_valid),
    .auto_in_d_bits_opcode                     (_buffer_auto_in_d_bits_opcode),
    .auto_in_d_bits_param                      (_buffer_auto_in_d_bits_param),
    .auto_in_d_bits_size                       (_buffer_auto_in_d_bits_size),
    .auto_in_d_bits_source                     (_buffer_auto_in_d_bits_source),
    .auto_in_d_bits_sink                       (_buffer_auto_in_d_bits_sink),
    .auto_in_d_bits_denied                     (_buffer_auto_in_d_bits_denied),
    .auto_in_d_bits_data                       (_buffer_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt                    (_buffer_auto_in_d_bits_corrupt),
    .auto_out_a_ready                          (auto_tl_master_clock_xing_out_a_ready),
    .auto_out_a_valid                          (auto_tl_master_clock_xing_out_a_valid),
    .auto_out_a_bits_opcode                    (auto_tl_master_clock_xing_out_a_bits_opcode),
    .auto_out_a_bits_param                     (auto_tl_master_clock_xing_out_a_bits_param),
    .auto_out_a_bits_size                      (auto_tl_master_clock_xing_out_a_bits_size),
    .auto_out_a_bits_source                    (auto_tl_master_clock_xing_out_a_bits_source),
    .auto_out_a_bits_address                   (auto_tl_master_clock_xing_out_a_bits_address),
    .auto_out_a_bits_user_amba_prot_bufferable (auto_tl_master_clock_xing_out_a_bits_user_amba_prot_bufferable),
    .auto_out_a_bits_user_amba_prot_modifiable (auto_tl_master_clock_xing_out_a_bits_user_amba_prot_modifiable),
    .auto_out_a_bits_user_amba_prot_readalloc  (auto_tl_master_clock_xing_out_a_bits_user_amba_prot_readalloc),
    .auto_out_a_bits_user_amba_prot_writealloc (auto_tl_master_clock_xing_out_a_bits_user_amba_prot_writealloc),
    .auto_out_a_bits_user_amba_prot_privileged (auto_tl_master_clock_xing_out_a_bits_user_amba_prot_privileged),
    .auto_out_a_bits_user_amba_prot_secure     (auto_tl_master_clock_xing_out_a_bits_user_amba_prot_secure),
    .auto_out_a_bits_user_amba_prot_fetch      (auto_tl_master_clock_xing_out_a_bits_user_amba_prot_fetch),
    .auto_out_a_bits_mask                      (auto_tl_master_clock_xing_out_a_bits_mask),
    .auto_out_a_bits_data                      (auto_tl_master_clock_xing_out_a_bits_data),
    .auto_out_a_bits_corrupt                   (auto_tl_master_clock_xing_out_a_bits_corrupt),
    .auto_out_d_ready                          (auto_tl_master_clock_xing_out_d_ready),
    .auto_out_d_valid                          (auto_tl_master_clock_xing_out_d_valid),
    .auto_out_d_bits_opcode                    (auto_tl_master_clock_xing_out_d_bits_opcode),
    .auto_out_d_bits_param                     (auto_tl_master_clock_xing_out_d_bits_param),
    .auto_out_d_bits_size                      (auto_tl_master_clock_xing_out_d_bits_size),
    .auto_out_d_bits_source                    (auto_tl_master_clock_xing_out_d_bits_source),
    .auto_out_d_bits_sink                      (auto_tl_master_clock_xing_out_d_bits_sink),
    .auto_out_d_bits_denied                    (auto_tl_master_clock_xing_out_d_bits_denied),
    .auto_out_d_bits_data                      (auto_tl_master_clock_xing_out_d_bits_data),
    .auto_out_d_bits_corrupt                   (auto_tl_master_clock_xing_out_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  IntSyncSyncCrossingSink_n1x2 intsink_1 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
    .auto_in_sync_0 (auto_int_in_clock_xing_in_0_sync_0),
    .auto_out_0     (_intsink_1_auto_out_0)
  );	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
  IntSyncCrossingSource_n1x1 intsource (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_tap_clock_in_clock),
    .reset           (auto_tap_clock_in_reset),
    .auto_in_0       (1'h0),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25, generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31, generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9, generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_out_sync_0 (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
  IntSyncCrossingSource_n1x1 intsource_1 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_tap_clock_in_clock),
    .reset           (auto_tap_clock_in_reset),
    .auto_in_0       (1'h0),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25, generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31, generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9, generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_out_sync_0 (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
  IntSyncCrossingSource_n1x1 intsource_2 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_tap_clock_in_clock),
    .reset           (auto_tap_clock_in_reset),
    .auto_in_0       (1'h0),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25, generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31, generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9, generators/rocket-chip/src/main/scala/subsystem/HasTiles.scala:164:59]
    .auto_out_sync_0 (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
endmodule

