// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLFIFOFixer_4(	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  output        auto_anon_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_anon_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_anon_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_anon_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [30:0] auto_anon_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_anon_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_anon_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_anon_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_anon_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_anon_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_anon_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_anon_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_anon_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [30:0] auto_anon_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_anon_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_anon_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_anon_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_anon_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_anon_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_anon_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_anon_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire [2:0]  _a_id_T_5 = auto_anon_in_a_bits_address[30:28] ^ 3'h5;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:31]
  wire [1:0]  a_id = {2{{_a_id_T_5[2], _a_id_T_5[0]} == 2'h0}} | {{~(auto_anon_in_a_bits_address[30]), auto_anon_in_a_bits_address[28]} == 2'h0, ~(auto_anon_in_a_bits_address[30])};	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46,59}, src/main/scala/chisel3/util/Mux.scala:30:73]
  reg  [9:0]  a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire        a_first = a_first_counter == 10'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  reg  [9:0]  d_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  reg         flight_0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_1;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_2;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg         flight_3;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27]
  reg  [1:0]  stalls_id;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30]
  wire        stall = a_first & (flight_0 | flight_1 | flight_2 | flight_3) & (a_id == 2'h0 | stalls_id != a_id);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:63:29, :79:27, :85:30, :88:{26,44,50,65,71}, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire        anonIn_a_ready = auto_anon_out_a_ready & ~stall;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:88:{26,50}, :95:50, :96:33]
  wire [26:0] _a_first_beats1_decode_T = 27'hFFF << auto_anon_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [26:0] _d_first_beats1_decode_T = 27'hFFF << auto_anon_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire        d_first_first = d_first_counter == 10'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  wire        _GEN = d_first_first & auto_anon_out_d_bits_opcode != 3'h6 & auto_anon_in_d_ready & auto_anon_out_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:{42,63}, :81:21, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _stalls_id_T_3 = anonIn_a_ready & auto_anon_in_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:96:33, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _GEN_0 = a_first & _stalls_id_T_3;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:80:21, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      a_first_counter <= 10'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      d_first_counter <= 10'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      flight_0 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
      flight_1 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
      flight_2 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
      flight_3 <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      if (_stalls_id_T_3)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        a_first_counter <= a_first ? (auto_anon_in_a_bits_opcode[2] ? 10'h0 : ~(_a_first_beats1_decode_T[11:2])) : a_first_counter - 10'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
      if (auto_anon_in_d_ready & auto_anon_out_d_valid)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        d_first_counter <= d_first_first ? (auto_anon_out_d_bits_opcode[0] ? ~(_d_first_beats1_decode_T[11:2]) : 10'h0) : d_first_counter - 10'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
      flight_0 <= ~(_GEN & auto_anon_out_d_bits_source == 2'h0) & (_GEN_0 & auto_anon_in_a_bits_source == 2'h0 | flight_0);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_1 <= ~(_GEN & auto_anon_out_d_bits_source == 2'h1) & (_GEN_0 & auto_anon_in_a_bits_source == 2'h1 | flight_1);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_2 <= ~(_GEN & auto_anon_out_d_bits_source == 2'h2) & (_GEN_0 & auto_anon_in_a_bits_source == 2'h2 | flight_2);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      flight_3 <= ~(_GEN & (&auto_anon_out_d_bits_source)) & (_GEN_0 & (&auto_anon_in_a_bits_source) | flight_3);	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:42, :79:27, :80:{21,35,62}, :81:{21,35,62}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    end
    if (_stalls_id_T_3)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      stalls_id <= a_id;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30, src/main/scala/chisel3/util/Mux.scala:30:73]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        a_first_counter = _RANDOM[/*Zero width*/ 1'b0][9:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        d_first_counter = _RANDOM[/*Zero width*/ 1'b0][19:10];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
        flight_0 = _RANDOM[/*Zero width*/ 1'b0][20];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_1 = _RANDOM[/*Zero width*/ 1'b0][21];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_2 = _RANDOM[/*Zero width*/ 1'b0][22];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        flight_3 = _RANDOM[/*Zero width*/ 1'b0][23];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27]
        stalls_id = _RANDOM[/*Zero width*/ 1'b0][25:24];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :85:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_31 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (anonIn_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:96:33]
    .io_in_a_valid        (auto_anon_in_a_valid),
    .io_in_a_bits_opcode  (auto_anon_in_a_bits_opcode),
    .io_in_a_bits_size    (auto_anon_in_a_bits_size),
    .io_in_a_bits_source  (auto_anon_in_a_bits_source),
    .io_in_a_bits_address (auto_anon_in_a_bits_address),
    .io_in_a_bits_mask    (auto_anon_in_a_bits_mask),
    .io_in_d_ready        (auto_anon_in_d_ready),
    .io_in_d_valid        (auto_anon_out_d_valid),
    .io_in_d_bits_opcode  (auto_anon_out_d_bits_opcode),
    .io_in_d_bits_param   (auto_anon_out_d_bits_param),
    .io_in_d_bits_size    (auto_anon_out_d_bits_size),
    .io_in_d_bits_source  (auto_anon_out_d_bits_source),
    .io_in_d_bits_sink    (auto_anon_out_d_bits_sink),
    .io_in_d_bits_denied  (auto_anon_out_d_bits_denied),
    .io_in_d_bits_corrupt (auto_anon_out_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  assign auto_anon_in_a_ready = anonIn_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :96:33]
  assign auto_anon_in_d_valid = auto_anon_out_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_in_d_bits_opcode = auto_anon_out_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_in_d_bits_size = auto_anon_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_in_d_bits_denied = auto_anon_out_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_in_d_bits_data = auto_anon_out_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_in_d_bits_corrupt = auto_anon_out_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_valid = auto_anon_in_a_valid & ~stall;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :88:{26,50}, :95:{33,50}]
  assign auto_anon_out_a_bits_opcode = auto_anon_in_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_size = auto_anon_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_source = auto_anon_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_address = auto_anon_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_user_amba_prot_bufferable = auto_anon_in_a_bits_user_amba_prot_bufferable;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_user_amba_prot_modifiable = auto_anon_in_a_bits_user_amba_prot_modifiable;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_user_amba_prot_readalloc = auto_anon_in_a_bits_user_amba_prot_readalloc;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_user_amba_prot_writealloc = auto_anon_in_a_bits_user_amba_prot_writealloc;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_user_amba_prot_privileged = auto_anon_in_a_bits_user_amba_prot_privileged;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_user_amba_prot_secure = auto_anon_in_a_bits_user_amba_prot_secure;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_user_amba_prot_fetch = auto_anon_in_a_bits_user_amba_prot_fetch;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_mask = auto_anon_in_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_a_bits_data = auto_anon_in_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
  assign auto_anon_out_d_ready = auto_anon_in_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9]
endmodule

