// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module TLMonitor_35(	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
  input        clock,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
  input        reset,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:36:7]
  input        io_in_a_valid,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_a_bits_param,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [1:0]  io_in_a_bits_size,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [2:0]  io_in_a_bits_source,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [30:0] io_in_a_bits_address,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input [3:0]  io_in_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
  input        io_in_a_bits_corrupt	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14]
);

  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
    wire       _source_ok_T = io_in_a_bits_source == 3'h4;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9]
    wire       source_ok = _source_ok_T | ~(io_in_a_bits_source[2]);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
    wire [4:0] _is_aligned_mask_T = 5'h3 << io_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
    wire [1:0] _GEN = io_in_a_bits_address[1:0] & ~(_is_aligned_mask_T[1:0]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:16, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
    wire       mask_sub_0_1 = io_in_a_bits_size[1] | io_in_a_bits_size[0] & ~(io_in_a_bits_address[1]);	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :210:26, :211:20, :215:{29,38}, src/main/scala/chisel3/util/OneHot.scala:64:49]
    wire       mask_sub_1_1 = io_in_a_bits_size[1] | io_in_a_bits_size[0] & io_in_a_bits_address[1];	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :210:26, :215:{29,38}, src/main/scala/chisel3/util/OneHot.scala:64:49]
    wire [3:0] mask = {mask_sub_1_1 | io_in_a_bits_address[1] & io_in_a_bits_address[0], mask_sub_1_1 | io_in_a_bits_address[1] & ~(io_in_a_bits_address[0]), mask_sub_0_1 | ~(io_in_a_bits_address[1]) & io_in_a_bits_address[0], mask_sub_0_1 | ~(io_in_a_bits_address[1]) & ~(io_in_a_bits_address[0])};	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27, :215:29, :222:10]
    wire       _GEN_0 = io_in_a_valid & io_in_a_bits_opcode == 3'h6 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:{25,54}]
    wire       _GEN_1 = io_in_a_bits_param > 3'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
    wire       _GEN_2 = io_in_a_bits_mask != 4'hF;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:91:31]
    wire       _GEN_3 = io_in_a_valid & (&io_in_a_bits_opcode) & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:{25,53}]
    wire       _GEN_4 = _source_ok_T | ~(io_in_a_bits_source[2]);	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:46:9, :54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1175:43]
    wire       _GEN_5 = io_in_a_valid & io_in_a_bits_opcode == 3'h4 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:{25,45}]
    wire       _GEN_6 = io_in_a_bits_size != 2'h3 & io_in_a_bits_address[30:28] == 3'h6;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:92:38, :137:{41,46,59}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:20:14, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:684:54]
    wire       _GEN_7 = io_in_a_bits_mask != mask;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, generators/rocket-chip/src/main/scala/util/Misc.scala:222:10]
    wire       _GEN_8 = _GEN_4 & _GEN_6;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:118:71, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:684:54, :1175:43]
    wire       _GEN_9 = io_in_a_valid & io_in_a_bits_opcode == 3'h0 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:{25,53}]
    wire       _GEN_10 = io_in_a_valid & io_in_a_bits_opcode == 3'h1 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:{25,56}]
    wire       _GEN_11 = io_in_a_valid & io_in_a_bits_opcode == 3'h2 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:{25,56}]
    wire       _GEN_12 = io_in_a_valid & io_in_a_bits_opcode == 3'h3 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:{25,53}]
    wire       _GEN_13 = io_in_a_valid & io_in_a_bits_opcode == 3'h5 & ~reset;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:{25,46}]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      if (_GEN_0) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock type which is unexpected using diplomatic parameters (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock from a client which does not support Probe (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_0 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid source ID (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_0 & ~(io_in_a_bits_size[1])) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock smaller than a beat (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_0 & (|_GEN)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock address not aligned to size (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_0 & _GEN_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid grow param (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_0 & _GEN_2) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54, :91:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock contains invalid mask (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_0 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :84:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquireBlock is corrupt (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm type which is unexpected using diplomatic parameters (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm from a client which does not support Probe (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid source ID (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & ~(io_in_a_bits_size[1])) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm smaller than a beat (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & (|_GEN)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm address not aligned to size (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & _GEN_1) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:111:27, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid grow param (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & ~(|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53, :102:31]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm requests NtoB (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & _GEN_2) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :91:31, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm contains invalid mask (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_3 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :95:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel AcquirePerm is corrupt (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & ~_GEN_4) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1175:43]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Get type which master claims it can't emit (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & ~_GEN_6) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:684:54]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Get type which slave claims it can't support (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get carries invalid source ID (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & (|_GEN)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get address not aligned to size (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :102:31, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get carries invalid param (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45, :113:30]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get contains invalid mask (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_5 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :107:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Get is corrupt (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & ~_GEN_8) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:53, :118:71]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries PutFull type which is unexpected using diplomatic parameters (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:53, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid source ID (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & (|_GEN)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull address not aligned to size (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :102:31, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid param (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_9 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :117:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutFull contains invalid mask (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & ~_GEN_8) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :118:71, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries PutPartial type which is unexpected using diplomatic parameters (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid source ID (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & (|_GEN)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial address not aligned to size (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & (|io_in_a_bits_param)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :102:31, :125:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid param (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_10 & (|(io_in_a_bits_mask & ~mask))) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :125:56, :130:{31,33,40}, generators/rocket-chip/src/main/scala/util/Misc.scala:222:10]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel PutPartial contains invalid mask (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_11) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Arithmetic type which is unexpected using diplomatic parameters (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_11 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid source ID (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_11 & (|_GEN)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic address not aligned to size (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_11 & io_in_a_bits_param > 3'h4) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:141:33, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid opcode param (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_11 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :133:56]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Arithmetic contains invalid mask (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Logical type which is unexpected using diplomatic parameters (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical carries invalid source ID (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & (|_GEN)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical address not aligned to size (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & io_in_a_bits_param[2]) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:148:30, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical carries invalid opcode param (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_12 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :141:53]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Logical contains invalid mask (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel carries Hint type which is unexpected using diplomatic parameters (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13 & ~source_ok) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:1139:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint carries invalid source ID (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13 & (|_GEN)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:21:{16,24}, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint address not aligned to size (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13 & (|(io_in_a_bits_param[2:1]))) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Bundles.scala:161:28, generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint carries invalid opcode param (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :113:30, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint contains invalid mask (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
      if (_GEN_13 & io_in_a_bits_corrupt) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11, :149:46]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $error("Assertion failed: 'A' channel Hint is corrupt (connected at generators/serv/src/main/scala/ServTile.scala:236:13)\n    at Monitor.scala:45 assert(cond, message)\n");	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/Monitor.scala:45:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  plusarg_reader #(
    .DEFAULT(0),
    .FORMAT("tilelink_timeout=%d"),
    .WIDTH(32)
  ) plusarg_reader_1 (	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (/* unused */)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
endmodule

