// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLSourceShrinker_1(	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  output        auto_anon_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_anon_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_anon_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_anon_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_anon_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [30:0] auto_anon_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_anon_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_anon_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_anon_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_anon_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_anon_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_anon_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_anon_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_anon_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_anon_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [30:0] auto_anon_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_bufferable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_modifiable,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_readalloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_writealloc,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_privileged,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_secure,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_user_amba_prot_fetch,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_anon_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_anon_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_anon_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_anon_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_anon_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_anon_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_anon_out_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  reg  [2:0]  sourceIdMap;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
  reg         full;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:59:32]
  reg  [7:0]  a_first_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire        a_first = a_first_counter == 8'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
  reg  [7:0]  d_last_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire        block = a_first & full;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:59:32, :67:29]
  wire        anonIn_a_ready = auto_anon_out_a_ready & ~block;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:67:29, :68:{35,38}]
  reg         anonOut_a_bits_source_r;	// @[generators/rocket-chip/src/main/scala/util/package.scala:88:63]
  wire [24:0] _a_first_beats1_decode_T = 25'h3FF << auto_anon_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire        _free_T = auto_anon_in_d_ready & auto_anon_out_d_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [24:0] _d_last_beats1_decode_T = 25'h3FF << auto_anon_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire [7:0]  d_last_beats1 = auto_anon_out_d_bits_opcode[0] ? ~(_d_last_beats1_decode_T[9:2]) : 8'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
  wire        _alloc_T = anonIn_a_ready & auto_anon_in_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:68:35, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
    if (a_first & _alloc_T)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:77:23, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      sourceIdMap <= auto_anon_in_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
    anonOut_a_bits_source_r <= ~a_first & anonOut_a_bits_source_r;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
      full <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:59:32]
      a_first_counter <= 8'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      d_last_counter <= 8'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
      full <= (full | a_first & _alloc_T & ~full) & ~((d_last_counter == 8'h1 | d_last_beats1 == 8'h0) & _free_T & ~auto_anon_out_d_bits_source);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :231:25, :232:{25,33,43}, generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:59:32, :60:35, :81:29, :82:27, :83:27, :84:26, :85:{19,33,45,47}, src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/chisel3/util/OneHot.scala:58:35]
      if (_alloc_T)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        a_first_counter <= a_first ? (auto_anon_in_a_bits_opcode[2] ? 8'h0 : ~(_a_first_beats1_decode_T[9:2])) : a_first_counter - 8'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, :221:14, :229:27, :230:28, :231:25, :236:21, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
      if (_free_T)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
        d_last_counter <= d_last_counter == 8'h0 ? d_last_beats1 : d_last_counter - 8'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :230:28, :231:25, :236:21]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
        sourceIdMap = _RANDOM[/*Zero width*/ 1'b0][20:18];	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9, :58:30]
        full = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9, :58:30, :59:32]
        a_first_counter = _RANDOM[/*Zero width*/ 1'b0][8:1];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9, :58:30]
        d_last_counter = _RANDOM[/*Zero width*/ 1'b0][16:9];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9, :58:30]
        anonOut_a_bits_source_r = _RANDOM[/*Zero width*/ 1'b0][17];	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9, :58:30, generators/rocket-chip/src/main/scala/util/package.scala:88:63]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_34 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (anonIn_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:68:35]
    .io_in_a_valid        (auto_anon_in_a_valid),
    .io_in_a_bits_opcode  (auto_anon_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_anon_in_a_bits_param),
    .io_in_a_bits_size    (auto_anon_in_a_bits_size),
    .io_in_a_bits_source  (auto_anon_in_a_bits_source),
    .io_in_a_bits_address (auto_anon_in_a_bits_address),
    .io_in_a_bits_mask    (auto_anon_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_anon_in_a_bits_corrupt),
    .io_in_d_ready        (auto_anon_in_d_ready),
    .io_in_d_valid        (auto_anon_out_d_valid),
    .io_in_d_bits_opcode  (auto_anon_out_d_bits_opcode),
    .io_in_d_bits_size    (auto_anon_out_d_bits_size),
    .io_in_d_bits_source  (sourceIdMap),	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
    .io_in_d_bits_denied  (auto_anon_out_d_bits_denied),
    .io_in_d_bits_corrupt (auto_anon_out_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  assign auto_anon_in_a_ready = anonIn_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9, :68:35]
  assign auto_anon_in_d_valid = auto_anon_out_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_in_d_bits_opcode = auto_anon_out_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_in_d_bits_size = auto_anon_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_in_d_bits_source = sourceIdMap;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9, :58:30]
  assign auto_anon_in_d_bits_denied = auto_anon_out_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_in_d_bits_data = auto_anon_out_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_in_d_bits_corrupt = auto_anon_out_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_valid = auto_anon_in_a_valid & ~block;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9, :67:29, :68:38, :69:35]
  assign auto_anon_out_a_bits_opcode = auto_anon_in_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_param = auto_anon_in_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_size = auto_anon_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_source = ~a_first & anonOut_a_bits_source_r;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9, generators/rocket-chip/src/main/scala/util/package.scala:88:{42,63}]
  assign auto_anon_out_a_bits_address = auto_anon_in_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_user_amba_prot_bufferable = auto_anon_in_a_bits_user_amba_prot_bufferable;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_user_amba_prot_modifiable = auto_anon_in_a_bits_user_amba_prot_modifiable;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_user_amba_prot_readalloc = auto_anon_in_a_bits_user_amba_prot_readalloc;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_user_amba_prot_writealloc = auto_anon_in_a_bits_user_amba_prot_writealloc;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_user_amba_prot_privileged = auto_anon_in_a_bits_user_amba_prot_privileged;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_user_amba_prot_secure = auto_anon_in_a_bits_user_amba_prot_secure;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_user_amba_prot_fetch = auto_anon_in_a_bits_user_amba_prot_fetch;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_mask = auto_anon_in_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_data = auto_anon_in_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_a_bits_corrupt = auto_anon_in_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
  assign auto_anon_out_d_ready = auto_anon_in_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:40:9]
endmodule

